export const Checkcolumn = [{
        title:'姓名',
        dataIndex:'name',
        key:'name'
     },{
         title:'车牌号',
         dataIndex:'car_number',
         key:'car_number'
     },{
        title:'电话号码',
        dataIndex:'phone',
        key:'phone'
     },{
        title:'申请人与车主关系',
        dataIndex:'relation',
        key:'relation'
}]
export const Allcolumn = [{
   title:'姓名',
   dataIndex:'name',
   key:'name'
},{
   title:'部门',
   dataIndex:'department',
   key:'department'
},{
    title:'车牌号',
    dataIndex:'car_number',
    key:'car_number'
},{
   title:'电话号码',
   dataIndex:'phone',
   key:'phone'
},{
   title:'申请人与车主关系',
   dataIndex:'relation',
   key:'relation'
}]